### ISSUE TITLE
Attempting to load incorrect components fails

### ISSUE THREAD

**Issue by tuckerzp** [EasyDynamics/oscal-react-library#137]
As a user of the OSCAL Viewer, I want to be able to not have the viewer crash when I load an incorrect component. 

### Steps to reproduce
1. Go to a component viewer. 
2. Load another type of component.

For example, loading https://raw.githubusercontent.com/usnistgov/oscal-content/master/examples/ssp/json/ssp-example.json into a catalog viewer causes the viewer to crash. 

### Acceptance Criteria
- Loading an incorrect component does not cause an outright crash
- An error message appears
- User has ability to reload another component after using incorrect one

**Comment by kylelaker** [comment]
It seems that this has been duplicated by #240 to fix the crash itself (and to ensure a more useful error message is displayed) and #163 which handles the fix for the "reload" button remaining disabled. The fix for #240 has already been merged; however, it remains open until a test has been written. #163 should be fixed in an soon-upcoming sprint.

**Comment by rgauss** [comment]
Closing this as a duplicate.
