### ISSUE TITLE
Handle 404 Responses in Local Production Build

### ISSUE THREAD

**Issue by hreineck** [EasyDynamics/oscal-react-library#164]
When the production build of the example OSCAL Viewer is served on localhost, refreshing any page, or navigating to any url besides `localhost:port`, (eg. localhost:5000/catalog) will cause a 404 response that shows an error page instead of the desired page.

## Steps to Reproduce

1. build the production build with `npm run build` in the `example` directory
2. serve the production build to localhost
3. view the viewer in a browser
4. refresh the page

## Acceptance Criteria

Pressing refresh when viewing the production build of the OSCAL Viewer refreshes the page instead of taking the user to an error page.
Navigating to any url in the production build of the Viewer acts as it would in the live demo.

**Comment by rgauss** [comment]
This is likely due to Spring Boot not knowing about the URL paths that React re-writes, so we should be able to configure to configure Spring to direct those known path requests to the static resources.

We currently [set the location of static resources through an environment variable in the Docker image](https://github.com/EasyDynamics/easygrc-deployment/blob/main/all-in-one/Dockerfile#L50).

**Comment by rgauss** [comment]
There was a similar issue in CloudFront that was [handled by transforming 404 errors from S3 into 200s pointing to /index.html](https://github.com/EasyDynamics/easygrc-infrastructure/blob/main/lib/easygrc-deployment-stack.ts#L66).
