### ISSUE TITLE
Address Dependabot Vulnerabilities

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#196]
As a consumer of the OSCAL React library, I want to be sure I'm not adding vulnerabilities through transitive dependencies highlighted by GitHub to my project so that I can remain secure and compliant.

### Acceptance Criteria
- There are no GitHub security alerts on the repository
- Ideally the Dependabot PRs have been merged

**Comment by kylelaker** [comment]
#250 took care of a significant number of the reported vulnerabilities in our dependencies' dependencies. There are only 4 security vulnerability reports remaining; however, they are all due to our transitive dependencies requiring specific old versions. As far as I can tell, these can all be "blamed" on `react-scripts`, `microbundle-crl`, and `@storybook/*`.

The same results shown by the Dependabot alerts can be found in `npm audit` so I will elaborate below.

The `glob-parent` issue is a ReDoS in a primarily dev dependency so likely has minimal impact. The `nth-check` issue is an Inefficient Regex Cox plexity issue also by a dependency of a dev dependency. The `postcss` issue is again a ReDoS in dependencies of dev dependencies. And `trim` again is ReDoS because of `@storybook/*` (and its dependencies).

Overall, these all are for our packaging scripts or within `storybook`. Because we deploy storybook and I'm not sure what is only local and what gets deployed, I don't want to entirely dismiss it; however, in our use case, ReDoS or inefficient regular expressions are of less concern than they may be in other situations.

I don't want to totally close the Dependabot security alerts just to get the count to 0 because then we're not quite as actively tracking them (and it can't be undone); however, there is nothing we can do for them at this time without forcing specific versions via `overrides` which may result in compatibility issues that would _actually_ break the application. Unfortunately, Dependabot security alerts don't seem to have a way to comment directly on the alert.

And as far as the disparity between `npm audit` and Dependabot, it seems that Dependabot only counts the actually broken package (so `trim`, `nth-check`, etc) whereas `npm audit` counts _all_ packages that consume it (such as `microbundle-crl`), resulting in a higher count.

**Comment by kylelaker** [comment]
For the Dependabot alerts specifically, the yellow banner on the repository is only visible to those who have access to security alerts; the default settings for which are:
![image](https://user-images.githubusercontent.com/850893/155433882-5faa77f8-dfac-4142-983c-9f425366e869.png)

Users _will_ still see a notice when they clone and `npm install` or `npm audit`, such as the following 
![image](https://user-images.githubusercontent.com/850893/155433976-cad4fc98-0c52-45a5-baa3-1db00ea6a4b3.png)

**Comment by hreineck** [comment]
@rgauss @mkeisen I created an issue to update the dependencies when they are ready: https://github.com/EasyDynamics/oscal-react-library/issues/317
