### ISSUE TITLE
Viewer Gives Error on Switch to SSP

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#239]
The viewer app in the sandbox environment currently shows an error when switching from catalog to SSP.

### Steps to Reproduce
1. Navigate to the [sandbox environment viewer](https://oscal-viewer.msd.easydynamics.com/)
2. Click the nav menu and click System Security Plan Viewer

### Expected Behavior
3. The default SSP renders

### Actual Behavior
3. An error is shown:
```
Yikes! Something went wrong loading the OSCAL data. Sorry, we'll look into it. (Unexpected token < in JSON at position 0)
```

### Implementation Notes
- We should be sure the behavior is fixed for all 'root' OSCAL objects, not just SSPs.

**Comment by kylelaker** [comment]
This, for me, seems to be an intermittent failure that occurs for all content types. Based on the error, it almost seems like HTML from somewhere is being parsed instead of JSON. If I refresh several times, it will work. I've seen this behavior for a little while now (at the time, I thought it was just related to some GitHub service issues).

We may want to consider adding `console.warn`s or something similar when there are failures in parsing. Oddly, I also don't see any errors in the Network tab of Dev Tools when this happens, which I'd expect if we were parsing a 4xx or 5xx error as JSON. This could be a race condition in some of our async stuff.

**Comment by kylelaker** [comment]
The error _could_ be due to CloudFront caching the old pages. Rather than invalidate the cache, I'll wait until tomorrow and re-evaluate then.
