### ISSUE TITLE
Create 0.3 Release of Viewer App

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#246]
As developer consuming the Viewer App I want to be able to pull a more recent viewer release so that I have the improved code without having to checkout and build.

### Acceptance Criteria
- A 0.3 release of the viewer app has been created

### Implementation Notes
- A user with write access to the repo can likely just manually trigger the 'Create a New Release' GitHub workflow and select 'feature' as the type

**Comment by kylelaker** [comment]
@hreineck I see you've self-assigned this. I know @zclarkEDC is still working on #240. I think the actual bug fix is done but there's still work being done on writing the necessary test(s). Would there be value in getting the actual fix parts of #240 into a PR and merged so it can be included in v0.3.0 and we can merge the tests after that window? And of course, there's always the option of just making v0.3.0 anyway since we can always create v0.4.0 later.

**Comment by kylelaker** [comment]
It looks like there's currently an issue with the release workflow where the `patch`/`bug` always gets triggered (https://github.com/EasyDynamics/oscal-react-library/actions/runs/1916708789). #290 fixes that.

**Comment by kylelaker** [comment]
The release has been created (https://github.com/EasyDynamics/oscal-react-library/releases/tag/v0.3.0) and a new issue #294 has been created to track future improvements to the release pipeline.
