### ISSUE TITLE
Loading of Non-Existent URL Doesn't Display Error

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#283]
Currently attempting to load a non-existent URL in the viewer does not display the error text.

### Steps to Reproduce
1. Load a non-existent URL into a the viewer app ([example](https://oscal-viewer.msd.easydynamics.com/system-security-plan?url=https://raw.githubusercontent.com/EasyDynamics/oscal-demo-content/bad-branch/system-security-plans/ssp-example.json))

### Expected Behavior
2. The red error notice should be displayed

### Actual Behavior
2. The loading spinner remains present and the console throws an error of:
```
Uncaught (in promise) Error: 404
    at OSCALLoader.js:95:1
```

**Comment by kylelaker** [comment]
This is likely due to the fix in #267 for #240. Error boundaries cannot catch/handle errors that occur [in an asynchronous context](https://reactjs.org/docs/error-boundaries.html#introducing-error-boundaries). The error here occurs within the `fetch` which is async. We can't (or don't want to) `await` the `fetch` (we use the asynchronous callbacks) so instead we need to find a way to catch the error and throw it again in a context where the Error Boundary _can_ handle it. We want to avoid having to add layers of `setError={setError}` into the components, so we'll want to look for another solution that allows us to handle this more seamlessly.

This _might_ be fixable in the short term by reverting the second commit in #267 (204b79609c9946ef1a47ce142975fb60d48acafd) but that feels short-sighted because it doesn't really provide a general solution.

**Comment by kylelaker** [comment]
https://medium.com/trabe/catching-asynchronous-errors-in-react-using-error-boundaries-5e8a5fd7b971 suggests that perhaps we could add a `setState` that `throw`s. And if we were to use a snippet like the one in that article, perhaps it could even be exported from the `ErrorBoundary.ts` file itself.

**Comment by rgauss** [comment]
@kylelaker, thoughts on a size here?

**Comment by kylelaker** [comment]
@rgauss Relatively about the same complexity as the open source tasks; 3?
