### ISSUE TITLE
Publish Package to npmjs

### ISSUE THREAD

**Issue by pkothare** [EasyDynamics/oscal-react-library#310]
If you strictly follow the guidance listed at: https://github.com/EasyDynamics/oscal-react-library/packages/1286914, then you end up with the following issue.

```bash
$ npm install @easydynamics/oscal-react-library@0.5.0-0
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@easydynamics%2foscal-react-library - Not found
npm ERR! 404
npm ERR! 404  '@easydynamics/oscal-react-library@0.5.0-0' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pkothare/.npm/_logs/2022-03-06T11_32_29_567Z-debug-0.log
```
This is because the package is published to GitHub and isn't being published to npm registry.

### Story
As a consumer, I would like to pull the OSCAL react library from npm registry, so that I do not have to perform additional configuration to start developing with the package.

### Implementation Notes
Follow the guidance provided at [Publishing packages to the npm registry](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry)

**Comment by kylelaker** [comment]
> If you strictly follow the guidance listed at: https://github.com/EasyDynamics/oscal-react-library/packages/1286914, then you end up with the following issue.

<details>
<summary>Rant on how that page works works</summary>
Those instructions (with the `npm install` command) aren't written by us unfortunately -- they're automatically inserted by GitHub Packages with the assumption that the user has followed the instructions for [Installing a package](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#installing-a-package).

The recommendation in those docs is to login to the GitHub packages registry and create either `./.npmrc` or `~/.npmrc` with the content:

```
@OWNER:registry=https://npm.pkg.github.com
```

So in our case:

```
@easydynamics:registry=https://npm.pkg.github.com
```

I do agree that it would be preferable for things to "just work" but I think each registry writes its installation docs with the assumption that users have already configured their environment to pull from that registry. But it's unfortunate that GitHub doesn't make that more prominent on their pages (since they're unlikely to be anyone's default).
</details>

We talked about using NPM briefly in the implementation of EGRC-492 (and in the review for #168). Based on the docs you linked, we'll need to find a clean/easy way to publish to both registries (as they each only show publishing to one or the other); or we'll need to choose to publish to NPM _instead_.

**Comment by kylelaker** [comment]
Having looked into this a bit more, it seems like all of the solutions to publish to multiple registries are a little hacky. In general, `npm` only supports having a single registry configured (technically, I suppose, it's one-registry-per-scope, though since we're talking about a single scope here, `@EasyDynamics/` XOR the "global" scope, that distinction isn't especially relevant). There are some workarounds but all seem to involve semi-dynamically reconfiguring `npm` to change the registry configuration.

One thing we probably want to be careful of is to make sure that the _exact same artifact_ is uploaded to each registry (so should have the same hash). From what I've seen, a lot of tools will rebuild/repack for each registry. This _may_ generate (...almost certainly generates...) different build artifacts.

I'm almost tempted recommend that we prefer publishing to NPM since that's the easiest thing for users to configure (as the default) and likely makes the package slightly more accessible.

**Comment by kylelaker** [comment]
https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#publish-to-npmjs-and-gpr-with-npm
