### ISSUE TITLE
Subtask: Disallow tests passing with warnings

### ISSUE THREAD

**Issue by tuckerzp** [EasyDynamics/oscal-react-library#450]

**Comment by kylelaker** [comment]
I don't want to do this. In general, we do want to allow warnings in certain (many) situations. We may have a dependency (let's say we're using 2.4.2 today) that has an update available (imagine 2.5.0). 2.5.0 may introduce deprecation warnings and other warnings to prepare for some future 3.0.0 release; but 2.5.0 may have security or bug fixes that we care about! We want to be able to adopt 2.5.0 trivially without fixing warnings about deprecations we won't care about for awhile (but we should track that as work we will need to do).

There may also be times where a dependency also introduces a bug (like MUI did recently) that adds warnings. Should we reject that update just because it has a non-breaking bug?

If we have a PR that introduces a feature that exposes causes a library to log a warning (and isn't an error in that PR itself), should we reject the feature entirely while we wait for that dependency to potentially fix those logged warnings?

We should probably create a practice of checking the test execution output to see if there are new warnings but I don't think we should reject a PR just because of that.

**Comment by tuckerzp** [comment]
Ok yeah that makes sense. I was not thinking about the fact that dependencies also cause errors when I made this issue. I agree we should be careful about not adding warnings in the future.
