### ISSUE TITLE
Subtask: Create `Object Selector` component

### ISSUE THREAD

**Issue by tuckerzp** [EasyDynamics/oscal-react-library#468]
Here is a proposed design of the `OSCALDrawerSelector` functionality:
- Drawer ~grows to a max width of 20% of total screen~ has a width of `250px`
  - Anything name longer than that max width will be truncated.
  - ~Content currently on screen is pushed to the side, rather than being covered.~
- Drawer is vertically scrollable.
- Items displayed will be placed under the following category hierarchy:
```
v easygrc-demo-content
  > catalogs
  > profiles
  v component-definitions
     Test Component Definition 1      // This is the metadata.title attribute of the component definition 
     Test Component Definition 2
  > system-security-plans
```
- Clicking on a directory displays the content within.
- Clicking on a file loads said file in the correct view.

**Comment by kylelaker** [comment]
Once the drawer is open, I don't think it should automatically resize. I'd almost prefer that it just was always 20% of screen size if that's the width we go with. We want to avoid things shifting around too much just because users are expanding/collapsing things. If a user were to drag something to resize or scroll that'd be a different matter but why not just statically set it to some %?

I also think, at least on the UI side of this, we may want to avoid the "Directory" and "File" names as well as any sort of assumption about some kind of root structure. We don't know that there's something named `oscal-demo-content` because that's not available via the API. We also probably want to capitalize the document names.

Otherwise, I think this is perfect for an initial implementation. In the _future_ we could consider doing fancier things like showing version numbers or other metadata. I don't think we need to do that in the MVP but the implementation should probably consider that we'd want to expand on it in the future (if that even is relevant).

So maybe I'd suggest the following:

```text
v Catalogs
  NIST SP 800-53 Rev. 5
  NIST SP 800-171
> Profiles
v Component Definitions
  Test Component Definition 1
  Test Component Definition 2
> System Security Plans
```

I also have no opinion on covering vs moving content -- I think, at least initially, we should go with whichever is easier to implement and then adjust based on any user feedback we may get.
