### ISSUE TITLE
CONTRIBUTING.md link broken in README.md

### ISSUE THREAD

**Issue by showalter** [EasyDynamics/oscal-react-library#563]
### Description

Clicking on the CONTRIBUTING.md link in the repository's README leads to a 404 page with the following error:

`The 'EasyDynamics/oscal-react-library' repository doesn't contain the 'CONTRIBUTING.md' path in 'develop'.`

### Steps to Reproduce

The issue may be a permissions problem since I'm not in the GitHub organization, so start with a browser session that isn't logged into a GitHub account in the organization.

From https://github.com/EasyDynamics/oscal-react-library#contributing click on the CONTRIBUTING.md link

### Expected behavior

I expected to be taken to a page with guidelines for contributing to the project.

### Actual Behavior

I was taken to a 404 page with the following error message:

`The 'EasyDynamics/oscal-react-library' repository doesn't contain the 'CONTRIBUTING.md' path in 'develop'.`

**Comment by showalter** [comment]
A quick note - when I was opening a PR, there was a pop up that brought me to https://github.com/EasyDynamics/.github/blob/7a6080770f02741158f0bfa3a256139ed866ea9a/CONTRIBUTING.md and that link works perfectly fine.

**Comment by kylelaker** [comment]
Oh oops! Thanks for catching this! We actually moved all our contributing docs to the [`EasyDynamics/.github`](https://github.com/EasyDynamics/.github) to have consistent base policies across the organization. We should have also updated our READMEs as part of this.

GitHub itself is very smart and links to the right place in pop-ups but unfortunately it can't make assumptions about our READMEs and other documentation.

We will work on making these updates in the very near future.

This bug was introduced in https://github.com/EasyDynamics/oscal-react-library/pull/221

**Comment by kylelaker** [comment]
Implementation note: When updating this across the various repositories, make sure to link to the file on the `main` branch of [`EasyDynamics/.github`](https://github.com/EasyDynamics/.github) to ensure we always link to the newest version.

**Comment by Bronstrom** [comment]
This bug was resolved across four of our repos in the following PRs: https://github.com/EasyDynamics/oscal-react-library/pull/566, https://github.com/EasyDynamics/oscal-editor-deployment/pull/138, https://github.com/EasyDynamics/oscal-rest-service/pull/126, and https://github.com/EasyDynamics/oscal-demo-content/pull/27.
