### ISSUE TITLE
Header Alignment Issue

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#603]
### Description

The "Powered by" and GitHub icon are no longer aligned to the right:

<img width="1172" alt="Screen Shot 2022-09-02 at 9 26 48 AM" src="https://user-images.githubusercontent.com/168671/188156363-6045bbd5-3f4e-4950-968b-f05fb6422210.png">

Apologies if this is a duplicate issue.

### Environment

https://oscal-viewer.msd.easydynamics.com/system-security-plan/

### Steps to Reproduce

Visit the public OSCAL viewer.

### Expected behavior

Header should look nice.

### Actual Behavior

Header doesn't look nice. :grin:

**Comment by kylelaker** [comment]
@rgauss Thanks for pointing this out. This was a semi-intentional decision made during #494 (or one of its siblings). I agree that this implementation, certainly in the viewer, is suboptimal. In the editor, we ran into a sorta clunkiness and busy-ness that caused readability issues and kinda hid the REST mode toggle and made the top corner too busy. Now, in the viewer we've got nothing over there and so it's just awkward and unbalanced.

So (and this is an ask for _everyone_) I think what I'd love to see is a proposal for a design of the app bar that works for both the viewer and the editor (even if it looks slightly different between them). We want the Easy Dynamics branding to be highly visible, we want to have the GitHub not masked by noise, and we want the REST mode toggle to be readable and understandable.

Some options might be moving the toggle to the App Drawer (at the bottom?) and using the old style for the app bar; using separators in the bar (`|`); or just rearranging things conditionally based on the app's status. Of course, other suggestions are welcome.

I am specifically going to ask @Bronstrom to take the lead on investigating this and proposing a specific design to solicit feedback on

**Comment by Bronstrom** [comment]
As @kylelaker had mentioned, this was a change made in #494 in an attempt to separate it from the "REST Mode" button from the "Powered by Easy Dynamics" and GitHub icon. Here's how it looks when running it locally:

![image](https://user-images.githubusercontent.com/35196021/188213285-5c3b2e92-e4dd-4752-83d1-329ba771ee6a.png)

I have two current ideas for handling this:
1. We can make a check to place this in the right corner when the REST button isn't present (like in the environment). Otherwise, this stays center.

2. We create a footer to place this content at the bottom of the of the application. #519 was created last month to address the placement of these items. This issue currently makes the header app bar and footer sticky, so this content is viewable on the screen at all times. I just attached a screenshot of the Viewer in the comments of this issue to give a better idea of what this looks like right now.

I personally am not a huge fan of where it is currently either, even when the REST mode button is present, so I'll probably opt for the second choice more.

**Comment by tuckerzp** [comment]
I still am a fan for #519. I think it is a clean way to deal with having things look consistent in the Viewer and Editor, without needing to add gross `isRestMode` if statements.

**Comment by kylelaker** [comment]
@Bronstrom 
![image](https://user-images.githubusercontent.com/850893/188220341-8eb71417-218c-49aa-8dd3-321e45459bf5.png)
