### ISSUE TITLE
Support viewing metadata `remarks`

### ISSUE THREAD

**Issue by Bronstrom** [EasyDynamics/oscal-react-library#710]
### Description

As an OSCAL content author, I want to view `remarks` in regard to metadata.

### Acceptance Criteria

- [ ] The 'remarks' field is properly displayed within the React library with proper formatting

### Proposed Solution

This could be displayed at the bottom of the metadata section, underneath the "Parties" panel.

### Implementation

- [ ] I can (or plan to) submit a pull request to implement this
- [ ] Implementing this may result in a breaking change

**Comment by tuckerzp** [comment]
For context https://pages.nist.gov/OSCAL/reference/latest/complete/json-reference/#/catalog/metadata/remarks

**Comment by brian-easyd** [comment]
Issue #689 builds on this. May want the same person to work both.

**Comment by tuckerzp** [comment]
## Proposed design

@EasyDynamics/oscal-editor-reviewers

### Background

Currently the page looks like https://oscal-viewer.msd.easydynamics.com/catalog/?url=https://raw.githubusercontent.com/EasyDynamics/oscal-demo-content/test-content/catalogs/basic-test-catalog.json

![image](https://user-images.githubusercontent.com/39490074/227991727-7ed5cad4-0a70-4313-b4a1-7c5db09968c7.png)

### Design

`metadata.remarks` can be handle with just a `markup-multiline` component. I imagine just having a text area in an accordion underneath Locations.

**Comment by kylelaker** [comment]
A modal for remarks doesn't seem especially useful. I think it'd be far better to display it above the accordions just as regular text. Maybe as `body2` text, and after some number of lines, have it truncate and a "See more" button that would expand to show the rest (to avoid several screen fulls of text).

I can see "Remarks" button being useful in the _general_ sense; especially since nearly every OSCAL object has them. We likely need something a little shorter than the word "Remarks" to use as an idiom (perhaps the [Comments](https://mui.com/material-ui/material-icons/?query=Comment&selected=Comment) icon?) that would fit in more places (with a useful `aria-label` or other attribute to maintain accessibility).

But I think at the metadata/document level, we have a little more room to display them (and the content may be a bit longer in some cases) than what you'd get for `remarks` on a `prop` on a `part` on a `control`.

I want to avoid making literally everything a dialog just because.
