### ISSUE TITLE
Support viewing a control's class

### ISSUE THREAD

**Issue by Bronstrom** [EasyDynamics/oscal-react-library#819]
### Description

As a user of the OSCAL Viewer/Editor, I would like to be able to view the class of a control.

### Acceptance Criteria

* The [`class` [0 or 1]](https://pages.nist.gov/OSCAL/reference/1.0.5/complete/json-reference/#/catalog/controls/class) attribute of a control is displayed properly
* The class display should be a re-usable component, such that it can be used for groups, params, and other OSCAL syntax that offers `@class`

### Proposed Solution

This could be the element that displays underneath a title of a sub-control and appears as the first element when a control grouping is expanded.

### Implementation

- [ ] I can (or plan to) submit a pull request to implement this
- [ ] Implementing this may result in a breaking change

**Comment by brian-easyd** [comment]
For initial implementation this will display all classes as if they are unrecognized. 

Later, the edit functionality ( #820) should offer a list of recognized classes, and for any recognized class, a user-friendly presentation would have to be provided here in addition to the raw presentation for unrecognized classes.

**Comment by kylelaker** [comment]
Here is the design that I have at the moment. I used the code we have for generating colors from a string to make it so that a particular string will always appear the same way -- this helps visually distinguish `SP800-53` from `sp800-53a` better. In the future, we might make these colors user-selectable?

![image](https://github.com/EasyDynamics/oscal-react-library/assets/850893/1af0c9bb-2b78-4d53-82c7-73cb94136e6b)

**Comment by tuckerzp** [comment]
> I used the code we have for generating colors from a string to make it so that a particular string will always appear the same way

I really like this design. I think being able to clearly distinguish class will be very helpful
